from big_ol_pile_of_manim_imports import *

class TitleScene(Scene):
    #Adding text on the screen
    def construct(self):
        title = TextMobject("\\begin{minipage}{2.3cm}\\begin{flushleft}Introduction to the \phantom{C} Programming Language\\end{flushleft}\\end{minipage}")
        c = TextMobject("\\begin{minipage}{2.3cm}\\begin{flushleft}\phantom{Introduction} \phantom{to} \phantom{the} C \phantom{Programming} \phantom{Language}\\end{flushleft}\\end{minipage}")
        title.set_color(SRCERY_BRIGHT_WHITE)
        c.set_color(SRCERY_GREEN)
        title.scale(2.5)
        title.shift(3*LEFT)
        c.scale(10)
        #c.shift(2.82*LEFT+0.85*UP)
         
        self.add(c)
        self.wait(2)
        self.play(ScaleInPlace(c, 0.25))
        self.play(ApplyMethod(c.shift, 2.82*LEFT+0.85*UP))
        self.play(ShowCreation(title))
        title.add(c)
        self.remove(c)
        self.play(FadeOut(title))
        #self.play(FadeOut(title))
        #self.play(FadeToColor(c, SRCERY_GREEN))
        #self.play(ScaleInPlace(c, 4))
        #self.add(title)
        #self.play(ScaleInPlace(title, 2))
        #self.play(ApplyMethod(title.shift, 3*LEFT))
        self.wait(2)
        self.add(AppleMac())
        self.wait(2)
        #self.play(Transform(second_line,third_line))
        #self.wait(2)
        #second_line.shift(3*DOWN)
        #self.play(ApplyMethod(my_first_text.shift,3*UP))
